---
version: "3.5"
x-extra_hosts:
  &default-extra_hosts
  - "erebor:192.168.0.38"
  - "erebor.local:192.168.0.38"
services:
  swag:
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    depends_on:
      - dockerproxy
    environment:
      - PUID=995
      - PGID=100
      - TZ=Europe/London
      - URL=${BASE_URL}
      - SUBDOMAINS=${SUBDOMAINS}
      - VALIDATION=${VALIDATION}
      - CERTPROVIDER= #optional
      - DNSPLUGIN=duckdns #optional
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN} #optional
      - EMAIL=${EMAIL} #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS=${EXTRA_DOMAINS} #optional
      - STAGING=false #optional
      - DOCKER_MODS=linuxserver/mods:universal-docker|linuxserver/mods:swag-auto-proxy|linuxserver/mods:swag-auto-reload|linuxserver/mods:swag-dashboard|linuxserver/mods:swag-cloudflare-real-ip|linuxserver/mods:universal-cloudflared
      - DOCKER_HOST=dockerproxy
    volumes:
      - web_gateway_swag_config:/config
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 80 #optional
        published: 80
        protocol: tcp
        mode: host
      - 81:81
    restart: unless-stopped
    networks:
      - web_gateway_webgateway_network
    extra_hosts: *default-extra_hosts
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    depends_on:
      - swag
    environment:
      - PUID=995
      - PGID=100
      - TZ=Europe/London
    volumes:
      - web_gateway_heimdall_config:/config
    restart: unless-stopped
    ports:
      - 50007:80
    labels:
      swag: enable
      swag_address: heimdall
      swag_port: 80
      swag_proto: http
      swag_url: heimdall.${BASE_URL}
    networks:
      - web_gateway_webgateway_network
    extra_hosts: *default-extra_hosts
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    environment:
      - CONTAINERS=1
      - POST=0
    networks:
      - web_gateway_webgateway_network
    extra_hosts: *default-extra_hosts
networks:
  web_gateway_webgateway_network:
    external: true
volumes:
  web_gateway_swag_config:
    external: true
  web_gateway_heimdall_config:
    external: true
