version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      - 50010:8123
    environment:
      EULA: "TRUE"
      TYPE: ${SERVER_TYPE}
      MEMORY: ${MAX_MEMORY}
      SPIGET_RESOURCES: ${SPIGOT_PLUGIN_IDS}
      WHITELIST: ${WHITELIST}
      OPS: ${OPS}
      SEED: ${SEED}
      MAX_PLAYERS: ${MAX_PLAYERS}
    labels:
      swag: enable
      swag_address: minecraft
      swag_port: 8123
      swag_proto: http
      swag_url: mc.${BASE_URL}
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - minecraft:/data
      - minecraft_plugins:/plugins
    networks:
      - web_gateway_webgateway_network
volumes:
  minecraft:
  minecraft_plugins:
networks:
  web_gateway_webgateway_network:
    external: true