version: "3"

services:
  minecraft_backup:
    image: itzg/mc-backup
    depends_on: minecraft
    restart: unless-stopped
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: minecraft
      PRE_BACKUP_SCRIPT: |
        echo "Before backup!"
        echo "Also before backup from $$RCON_HOST to $$DEST_DIR"
      POST_BACKUP_SCRIPT: |
        echo "Backup from $RCON_HOST to $DEST_DIR finished"
    volumes:
      # mount the same volume used by server, but read-only
      - minecraft:/data:ro
      # use a host attached directory so that it in turn can be backed up
      # to external/cloud storage
      - ${MINECRAFT_BACKUP_FOLDER}:/backups
  minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
      - 50010:8080
    environment:
      EULA: "TRUE"
      TYPE: ${SERVER_TYPE}
      INIT_MEMORY: 512M
      MAX_MEMORY: ${MAX_MEMORY}
      SPIGET_RESOURCES: ${SPIGOT_PLUGIN_IDS}
      WHITELIST: ${WHITELIST}
      OPS: ${OPS}
      SEED: ${SEED}
      MAX_PLAYERS: ${MAX_PLAYERS}
      USE_SIMD_FLAGS: true
      USE_AIKAR_FLAGS: true
      TUNE_VIRTUALIZED: FALSE
      TUNE_NURSERY_SIZES: FALSE
      ENABLE_ROLLING_LOGS: true
    labels:
      swag: enable
      swag_address: minecraft
      swag_port: 8080
      swag_proto: http
      swag_url: mc.${BASE_URL}
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - minecraft:/data
      - minecraft_plugins:/plugins
    networks:
      - web_gateway_webgateway_network
volumes:
  minecraft:
  minecraft_plugins:
networks:
  web_gateway_webgateway_network:
    external: true